language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
  - cargo install cargo-kcov
  - sudo apt-get install cmake g++ pkg-config jq
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
  - cargo kcov --print-install-kcov-sh | sh
  - cargo kcov --coveralls
