[package]
name = "extdot-impl"
version = "0.1.0"
authors = ["James Cassidy <qfire-vc@qfire.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
# proc-macro2 = "0.4"
proc-macro-hack = "0.5"
# quote = "0.6"
# syn = "0.15"
